# Generated by Django 3.1.1 on 2020-09-26 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20200924_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='coberturaEntrega',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='preferencias',
            field=models.ManyToManyField(to='main.Categoria'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_profile',
            field=models.OneToOneField(default='Default', on_delete=django.db.models.deletion.CASCADE, to='main.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cobertura_entrega',
            field=models.ManyToManyField(to='main.Localizacion'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='user_profile',
            field=models.OneToOneField(default='Default', on_delete=django.db.models.deletion.CASCADE, to='main.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(default='Default', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('MA', 'Masculino'), ('FE', 'Femenino'), ('NB', 'No Binario')], max_length=2),
        ),
    ]
