# Generated by Django 3.1.1 on 2020-10-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201010_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='apellidoMaterno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='apellidoPaterno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
